# start by pulling the python image
FROM python:latest

# copy the requirements file into the image
COPY requirements.txt requirements.txt

# switch working directory
WORKDIR /app

# install the dependencies and packages in the requirements file
RUN pip freeze > requirements.txt
RUN pip install -r ./requirements.txt

# copy every content from the local file to the image
COPY . .

# configure the container to run in an executed manner
ENTRYPOINT [ "python" ]

EXPOSE 8000

CMD ["app.py" ]